### ISSUE TITLE
Replacing social media logotypes

### ISSUE THREAD

**Issue by KateYatsiuk** [ita-social-projects/StreetCode_Client#923]
### **Description**
Need to replace the icons in the corresponding components (svg format) + add icon and link to telegram chanel.

### **Acceptance Criteria**
- All icons are in svg format.
- **Footer:** all logos match the design.
- **Burger menu:** all logos match the design.
- **Contact us:** all logos match the design.

### **Tasks**
- [ ]  Upload new logos in svg format.
- [ ] Change footer logos.
- [ ] Change menu logos.
- [ ] Change contact us logos.
